### ISSUE TITLE
Improve C doxygen documentation

### ISSUE THREAD

**Issue by mrpelotazo** [stackforce/serial-interface-mac#6]
By default doxygen puts enums, functions, etc. into the top level "Files" section, f.i. "Files>Globals>Functions" and from there one has to navigate into the source file to find the function. Needless to say this is not the best way to navigate the documentation.

Please use grouping commands to get a more navigable documentation. The following will add **Functions** and **Enums** to the **Modules** section in the documentation:

```C
/**
 * @defgroup Enums
 * Enumerations
 */

/**
 * @defgroup Functions
 * Functions
 */
/**
 * @ingroup Enums
 * @{
 * Indications to inform upper layer about problems processing incoming bytes.
 */
enum sf_serialmac_error
{
    /** The CRC of a received frame is not valid. */
    SF_SERIALMAC_ERROR_INVALID_CRC,
    /**
      * The first received byte is not a SYNC BYTE.
      * After this indication the control is handed back to the upper layer.
      */
    SF_SERIALMAC_ERROR_INVALID_SYNC_BYTE
};
/*@}*/


/**
 * @ingroup Functions
 * @{
 * Reset function of STACKFORCE Serial MAC.
 *
 * This function resets the variables and states in the ctx and can be
 * called whenever a reset of the state of the Serial MAC is needed
 * (e.g. after a timeout in the application).
 *
 * @param ctx Context to reset variables txFrame and rxFrame.
 * @return Error state.
 */
enum sf_serialmac_return sf_serialmac_reset ( struct sf_serialmac_ctx *ctx );
/*@}*/
```

Please apply this to all functions, enums, defines, etc.

**Comment by balo0801** [comment]
I agree that there should be at least one doxygen group in the header files to have them listed in the "Modules" section of doxygen.

With background of maintenance efforts and due to clearness there should be only one doxygengroup per header.
